/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BruitCore {
    'options': any;
  }
  interface BruitIo {}
  interface BruitRating {}
  interface BruitSelect {}
}

declare global {


  interface HTMLBruitCoreElement extends Components.BruitCore, HTMLStencilElement {}
  var HTMLBruitCoreElement: {
    prototype: HTMLBruitCoreElement;
    new (): HTMLBruitCoreElement;
  };

  interface HTMLBruitIoElement extends Components.BruitIo, HTMLStencilElement {}
  var HTMLBruitIoElement: {
    prototype: HTMLBruitIoElement;
    new (): HTMLBruitIoElement;
  };

  interface HTMLBruitRatingElement extends Components.BruitRating, HTMLStencilElement {}
  var HTMLBruitRatingElement: {
    prototype: HTMLBruitRatingElement;
    new (): HTMLBruitRatingElement;
  };

  interface HTMLBruitSelectElement extends Components.BruitSelect, HTMLStencilElement {}
  var HTMLBruitSelectElement: {
    prototype: HTMLBruitSelectElement;
    new (): HTMLBruitSelectElement;
  };
  interface HTMLElementTagNameMap {
    'bruit-core': HTMLBruitCoreElement;
    'bruit-io': HTMLBruitIoElement;
    'bruit-rating': HTMLBruitRatingElement;
    'bruit-select': HTMLBruitSelectElement;
  }
}

declare namespace LocalJSX {
  interface BruitCore {
    'options'?: any;
  }
  interface BruitIo {}
  interface BruitRating {}
  interface BruitSelect {}

  interface IntrinsicElements {
    'bruit-core': BruitCore;
    'bruit-io': BruitIo;
    'bruit-rating': BruitRating;
    'bruit-select': BruitSelect;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'bruit-core': LocalJSX.BruitCore & JSXBase.HTMLAttributes<HTMLBruitCoreElement>;
      'bruit-io': LocalJSX.BruitIo & JSXBase.HTMLAttributes<HTMLBruitIoElement>;
      'bruit-rating': LocalJSX.BruitRating & JSXBase.HTMLAttributes<HTMLBruitRatingElement>;
      'bruit-select': LocalJSX.BruitSelect & JSXBase.HTMLAttributes<HTMLBruitSelectElement>;
    }
  }
}


